apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-backend
  namespace: demo
spec:
  replicas: 4 # Subimos réplicas para ver mejor el Canary
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
      - name: backend
        image: image-registry.openshift-image-registry.svc:5000/demo/demo-backend:latest
        env:
        - name: DB_HOST
          value: "database-postgresql"
        - name: DB_NAME
          value: "app_db"
        - name: DB_USER
          value: "app_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
  strategy:
    canary:
      canaryService: demo-backend-canary # Apunta a tu service existente
      stableService: demo-backend
      steps:
      - setWeight: 25   # 1 pod nuevo (V2), 3 pods viejos (V1)
      - pause: {}       # Pausa manual para verificar
      - setWeight: 50   # 2 pods nuevos, 2 viejos
      - pause: {duration: 1m}
      - setWeight: 100  # Finaliza
---
apiVersion: v1
kind: Service
metadata:
  name: demo-backend # Este nombre es el que usará el frontend para conectar
  namespace: demo
  labels:
    app: demo-backend
spec:
  selector:
    app: demo-backend
  ports:
    - protocol: TCP
      name: web
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-backend-canary
  namespace: demo
spec:
  selector:
    app: demo-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
