---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-frontend
  namespace: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - name: web-server
        image: image-registry.openshift-image-registry.svc:5000/demo/mi-web:latest
        ports:
        - containerPort: 8080
  strategy:
    canary:
      # Estos nombres deben coincidir con los servicios de abajo
      stableService: demo-frontend
      canaryService: demo-frontend-canary
      steps:
      - setWeight: 25
      - pause: {} # Se detiene indefinidamente hasta que tú avances el rollout
      - setWeight: 50
      - pause:
          duration: 1m
      - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend # Haz lo mismo para el -canary
  namespace: demo
spec:
  selector:
    app: demo-frontend
    # No pongas el hash aquí, deja que Argo Rollouts lo gestione
  ports:
  - protocol: TCP
    port: 80         # Puerto del Servicio
    targetPort: 8080 # EL PUERTO QUE RESPONDIÓ BIEN (donde vive Nginx)
---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend-canary
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: 8080 # ¡IMPORTANTE! Debe ser el mismo que el estable
    protocol: TCP
    name: http
  selector:
    app: demo-frontend # Argo Rollouts gestionará el hash aquí