apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-frontend-route
  namespace: demo
spec:
  host: demo-frontend-route-demo.apps.ocp.sbox.anubix.tech
  to:
    kind: Service
    name: demo-frontend
    weight: 100
  alternateBackends:
  - kind: Service
    name: demo-frontend-canary
    weight: 0
  port:
    targetPort: 80 # Sigue apuntando al puerto 80 del Service
  tls:
    termination: edge # Esto añade el certificado SSL/TLS del cluster
    insecureEdgeTerminationPolicy: Allow # Permite entrar por http y redirigir o permitir