apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: web-build-listener
  namespace: demo
spec:
  serviceAccountName: pipeline
  triggers:
    - template:
        ref: web-build-template  # Cambiado de templateRef a template.ref
      bindings:
        - ref: web-build-binding  # Cambiado de bindingRef a bindings[0].ref