apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-build-workspace
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ssd-csi